env:
  JULIA_VERSION: "1.8.5"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1
  slurm_time: 24:00:00

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Targeted resolution AMIP long runs"

    steps:

      - label: ":computer: baroclinic wave (ρe_tot) equilmoist high resolution topography (earth)"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --topography Earth --moist equil --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 2e16 --initial_condition MoistBaroclinicWave --dt 100secs --t_end 100days --dt_save_to_disk 10days --job_id longrun_bw_rhoe_equil_highres_topography_earth --rayleigh_sponge true --alpha_rayleigh_uh 0.0 --alpha_rayleigh_w 1.0 --use_reference_state false --topo_smoothing true
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_bw_rhoe_equil_highres_topography_earth --out_dir longrun_bw_rhoe_equil_highres_topography_earth
        artifact_paths: "longrun_bw_rhoe_equil_highres_topography (earth)/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32
          slurm_mem: 128GB

      - label: ":computer: held suarez (ρe_tot) equilmoist high resolution topography (earth)"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --topography Earth --surface_setup DefaultExchangeCoefficients --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 3e16 --dt 100secs --t_end 400days --dt_save_to_disk 10days --job_id longrun_hs_rhoe_equil_highres_topography_earth --rayleigh_sponge true --alpha_rayleigh_uh 0.0 --alpha_rayleigh_w 1.0 --use_reference_state false --topo_smoothing true
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_hs_rhoe_equil_highres_topography_earth --out_dir longrun_hs_rhoe_equil_highres_topography_earth
        artifact_paths: "longrun_hs_rhoe_equil_highres_topography_earth/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64
          slurm_mem: 256GB

      - label: ":computer: no lim ARS aquaplanet (ρe_tot) equilmoist high resolution clearsky radiation Float64 (earth) 75s"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --vert_diff true --surface_setup DefaultMoninObukhov --moist equil --rad clearsky --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 3e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 75secs --t_end 300days --fps 30 --job_id longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth --dt_save_to_sol 10days --dt_save_to_disk 10days --FLOAT_TYPE Float64 --apply_limiter false --topography Earth --alpha_rayleigh_w 1.0 --use_reference_state false --topo_smoothing true
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth --out_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth --fig_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth --case_name aquaplanet
        artifact_paths: "longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 64
          slurm_mem: 256GB
      
      - label: ":computer: no lim ARS aquaplanet (ρe_tot) equilmoist high resolution clearsky radiation Float64 (earth) 100s"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --vert_diff true --surface_setup DefaultMoninObukhov --moist equil --rad clearsky --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 6e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 100secs --t_end 300days --fps 30 --job_id longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s --dt_save_to_sol 10days --dt_save_to_disk 10days --FLOAT_TYPE Float64 --apply_limiter false --topography Earth --alpha_rayleigh_w 1.0 --use_reference_state false --topo_smoothing true
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s --out_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s --fig_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s --case_name aquaplanet
        artifact_paths: "longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          RESTART_FILE: "/central/scratch/esm/slurm-buildkite/climaatmos-longruns/1070/climaatmos-longruns/longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s/day100.0.hdf5"
        agents:
          slurm_ntasks: 64
          slurm_mem: 256GB
      
      - label: ":computer: no lim ARS aquaplanet (ρe_tot) equilmoist high resolution clearsky radiation Float64 (earth) 100s"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --vert_diff true --surface_setup DefaultMoninObukhov --moist equil --rad clearsky --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 4e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 100secs --t_end 300days --fps 30 --job_id longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s --dt_save_to_sol 10days --dt_save_to_disk 1days --FLOAT_TYPE Float64 --apply_limiter false --topography Earth --alpha_rayleigh_w 1.0 --use_reference_state false --topo_smoothing true
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s --out_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s --fig_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s --case_name aquaplanet
        artifact_paths: "longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          RESTART_FILE: "/central/scratch/esm/slurm-buildkite/climaatmos-longruns/1070/climaatmos-longruns/longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s/day100.0.hdf5"
        agents:
          slurm_ntasks: 64
          slurm_mem: 256GB
      
      - label: ":computer: no lim ARS aquaplanet (ρe_tot) equilmoist high resolution clearsky radiation Float64 (earth) 100s limiter"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --vert_diff true --surface_setup DefaultMoninObukhov --moist equil --rad clearsky --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 6e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 100secs --t_end 300days --fps 30 --job_id longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s_limiter --dt_save_to_sol 10days --dt_save_to_disk 10days --FLOAT_TYPE Float64 --apply_limiter true --topography Earth --alpha_rayleigh_w 1.0 --use_reference_state false --topo_smoothing true
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s_limiter --out_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s_limiter
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s_limiter --fig_dir longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s_limiter --case_name aquaplanet
        artifact_paths: "longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s_limiter/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          RESTART_FILE: "/central/scratch/esm/slurm-buildkite/climaatmos-longruns/1070/climaatmos-longruns/longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64_earth_100s/day100.0.hdf5"
        agents:
          slurm_ntasks: 64
          slurm_mem: 256GB
