env:
  JULIA_VERSION: "1.8.5"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"
  CONFIG_PATH: "config/longrun_configs/"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1
  slurm_time: 24:00:00

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Targeted resolution AMIP long runs"

    steps:
      
      - label: ":computer: no lim ARS aquaplanet equilmoist clearsky radiation online diagnostic edmf"
        command:
          - mpiexec julia --project=examples examples/hybrid/driver.jl --config_file ${CONFIG_PATH}aquaplanet_clearsky_diagedmf_online.yml
          - julia --color=yes --project=examples post_processing/remap/remap_pipeline.jl --data_dir aquaplanet_clearsky_diagedmf_online --out_dir aquaplanet_clearsky_diagedmf_online
          - julia --color=yes --project=examples post_processing/plot/plot_pipeline.jl --nc_dir aquaplanet_clearsky_diagedmf_online --fig_dir aquaplanet_clearsky_diagedmf_online --case_name aquaplanet
        artifact_paths: "aquaplanet_clearsky_diagedmf_online/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 32
          slurm_mem_per_cpu: 16GB
      
