
rad: "clearsky" 
moist: "equil"
precip_model: "0M"
surface_setup: "DefaultExchangeCoefficients" 
hyperdiff: "false" 
config: "column" 
initial_condition: "IsothermalProfile" 
z_max: 70000
z_elem: 70 
dz_bottom: 100 
dz_top: 10000 
t_end: "1days" 
dt: "2secs" 
dt_rad: "3hours"
dt_save_to_sol: "Inf" 
dt_save_to_disk: "1hours" 
prognostic_surface: "true" 
turbconv: "diagnostic_edmfx" 
prognostic_tke: true
edmfx_upwinding: "first_order" 
edmfx_entr_detr: true 
edmfx_sgs_flux: true
job_id: "column_rce_clearsky_diagedmf_progsfctemp"
