job_id: diagnostic_edmfx_gabls_box
initial_condition: GABLS
edmf_coriolis: GABLS
surface_setup: GABLS
turbconv: diagnostic_edmfx
prognostic_tke: true
edmfx_upwinding: first_order
edmfx_entr_detr: true
edmfx_nh_pressure: true 
edmfx_sgs_flux: true
moist: equil
config: box
hyperdiff: "true"
kappa_4: 1e12
x_max: 1e5
y_max: 1e5
x_elem: 2
y_elem: 2
z_elem: 8
z_max: 400
z_stretch: false
dt: 10secs
t_end: 9hours
dt_save_to_disk: 10mins
