
job_id: diagnostic_edmfx_trmm_box
initial_condition: TRMM_LBA 
rad: TRMM_LBA 
surface_setup: TRMM_LBA
turbconv: diagnostic_edmfx 
prognostic_tke: true
edmfx_upwinding: first_order 
edmfx_entr_detr: true 
edmfx_nh_pressure: true 
edmfx_sgs_flux: true
moist: equil
apply_limiter: false
precip_model: "0M"
config: box 
hyperdiff: "true"
kappa_4: 1e12
x_max: 1e5 
y_max: 1e5 
x_elem: 2 
y_elem: 2 
z_elem: 82 
z_max: 16400 
z_stretch: false
dt: 10secs 
t_end: 6hours 
dt_save_to_disk: 10mins 
FLOAT_TYPE: "Float64"