
job_id: "diagnostic_edmfx_bomex_box"
initial_condition: "Bomex" 
subsidence: "Bomex" 
edmf_coriolis: "Bomex" 
ls_adv: "Bomex" 
surface_setup: "Bomex"
turbconv: "diagnostic_edmfx" 
prognostic_tke: true
edmfx_upwinding: "first_order" 
edmfx_entr_detr: true 
edmfx_nh_pressure: true 
edmfx_sgs_flux: true
moist: "equil"
config: "box" 
hyperdiff: "true" 
kappa_4: 1e12
x_max: 1e5 
y_max: 1e5 
x_elem: 2 
y_elem: 2 
z_elem: 60 
z_max: 3e3 
z_stretch: false
dt: "10secs" 
t_end: "6hours" 
dt_save_to_disk: "10mins"