edmf_coriolis: Bomex
dt_save_to_disk: 5mins
hyperdiff: "false"
z_elem: 60
dt: 20secs
debugging_tc: true
surface_setup: Bomex
turbconv_case: Bomex
t_end: 6hours
turbconv: "edmf"
z_stretch: false
config: column
subsidence: Bomex
FLOAT_TYPE: Float64
z_max: 3000.0
regression_test: true
ls_adv: Bomex
dt_save_to_sol: 5mins
job_id: edmf_bomex
moist: equil

