moist: "equil"
dt_save_to_disk: "1mins"
rayleigh_sponge: true
hyperdiff: "false"
z_elem: 82
dt: "0.1secs"
debugging_tc: true
surface_setup: "TRMM_LBA"
turbconv_case: "TRMM_LBA"
t_end: "1hours"
turbconv: "edmf"
z_stretch: false
config: "column"
FLOAT_TYPE: "Float64"
z_max: 16400.0
precip_model: "1M"
regression_test: true
dt_save_to_sol: "5mins"
job_id: "edmf_trmm"
rad: "TRMM_LBA"
toml: [toml/edmf_trmm.toml]
