rad: "clearsky"
dt_save_to_disk: "6hours"
rayleigh_sponge: true
z_elem: 35
dt: "5secs"
surface_setup: "DefaultMoninObukhov"
fps: 30
t_end: "1days"
dz_bottom: 50.0
h_elem: 12
kappa_4: 3.0e16
FLOAT_TYPE: "Float64"
apply_limiter: false
precip_model: "0M"
alpha_rayleigh_uh: 0.0
dt_save_to_sol: "Inf"
job_id: "aquaplanet_clearsky_diagedmf_online"
moist: "equil"
turbconv: diagnostic_edmfx 
prognostic_tke: true
edmfx_upwinding: first_order 
edmfx_entr_detr: true 
edmfx_sgs_flux: true
post_process: false
