dt_save_to_disk: "10days"
dt: "300secs" 
t_end: "1000days"
h_elem: 16
z_max: 55000.0
z_elem: 63
vert_diff: "true" 
kappa_4: 2e16
alpha_rayleigh_w: 1.0
surface_setup: "DefaultExchangeCoefficients" 
moist: "equil" 
rad: "gray" 
precip_model: "0M" 
job_id: "longrun_aquaplanet_rhoe_equil_gray_55km_nz64_0M" 
