config: "column" 
FLOAT_TYPE: "Float64" 
hyperdiff: "false" 
moist: "equil" 
rad: "TRMM_LBA" 
turbconv: "edmf" 
turbconv_case: "TRMM_LBA" 
precip_model: "1M" 
dt_save_to_sol: "5mins" 
z_elem: 90 
z_stretch: false 
z_max: 17000 
rayleigh_sponge: true 
job_id: "longrun_compressible_edmf_trmm" 
dt: "0.2secs" 
t_end: "3.8hours"
toml: [longrun_compressible_edmf_trmm.toml]
