dt_save_to_disk: "10days"
dt: "150secs"
t_end: "1000days"
h_elem: 16
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
z_max: 45000.0
kappa_4: 2.0e16
alpha_rayleigh_w: 10.0
vert_diff: "true"
moist: "equil"
precip_model: "0M"
rayleigh_sponge: true
zd_rayleigh: 35000.0
forcing: "held_suarez"
job_id: "longrun_hs_rhoe_equilmoist_nz64_0M_55km_rs35km"
output_dir: "/central/scratch/asridhar/Milestone_1-5-2a/"
